### PR TITLE
Alessandro Ferreira Martins

### PR DESCRIPTION
**Pull request by alessandro-f-martins**
- Added Python highlighting features
- Added Java highlighting features
- Set background colour to black
- Set sublimemonokai_term_italic to 1
- Created new colours and highlighting groups 
- Changed MatchParens to 'underline'
- Improved colourization for tabs in Wintabs (changed StatusLine. StatusLineNC and TabLineSel highlighting groups)

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
Hey there! Sorry for taking a while to get back to you -- I noticed that this was a large set of changes, and I wasn't able to dedicate the time I know I'm going to need for this PR during the weekend. I think I'm going to actually be able to handle this tomorrow, but I wanted to leave some feedback now so we could have some dialogue going before I dig too deeply into the details.

---

I've only taken a cursory look at your changes, but I'm reluctant to commit any of the following without further justification or discussion:

> * Set background colour to black
> * Set sublimemonokai_term_italic to 1
> ....
> * Changed MatchParens to 'underline'

At first blush, these seem to be indications of preference and not necessarily geared towards the goals of this repo. While I'm certainly open to changing Vim-specific highlights if they are argued to be better defaults, I have to mention now that some or all of these will probably be subject to my strong opinions.

---

> * Added Python highlighting features
> * Added Java highlighting features
> ....
> * Improved colourization for tabs in Wintabs (changed StatusLine. StatusLineNC and TabLineSel highlighting groups)

Yaaay! I'm excited to see what you've got. :)

---

I'm not sure about:

> * Created new colours and highlighting groups

This isn't specific, so it looks like I'll have to figure out what you mean tomorrow.

**Comment by ErichDonGubler** [comment]
I haven't forgotten about this PR! My personal life has kept me from doing any serious upkeep on this, but I plan on getting it to it soon.

**Comment by alessandro-f-martins** [comment]
Hi, Erich!

I have been quite busy in the last days as well. I will resume my activities on this development right away! Let's see about some of the points you highlighted:

- Set background colour to black
- Set sublimemonokai_term_italic to 1

Indeed, these ones are pretty personal. I like the way Monokai is sometimes rendered with full black background on Sublime Text; it just seems more natural to work with. Enabling italics is also pretty cool, especially for comments. 

- Added Python highlighting features
- Added Java highlighting features

These are more functional. I added some highlighting groups and colors to be able to encompass a bigger number of Java and Python features. Having made those adjustments, I complemented the highlighting groups matching those with the python.vim and java.vim default, out-of-the-box syntax scripts, especially with Python, which missed almost everything:-).

- Changed MatchParens to 'underline'
This one is pretty personal too, but with a reason: I particularly get a little confused with block-sized parentheses-matching markers; especially when the parentheses are close, it seems like your cursor is "dancing" back and forth in the line of code, which can be distracting

- Improved colourization for tabs in Wintabs (changed StatusLine. StatusLineNC and TabLineSel highlighting groups)
I am a user of Wintabs, and the original colours for the mentioned groups made the text and the background of the tabline too bright, with little contrast and hard to read. My mods made it match the full-black background of the active tab, while the other remain with the same colour as the basis tabline bar, but using the '\ue0b1' character to keep them separated.

Now, I would like to talk to you about what you see that makes sense in a broad project perspective and what I should keep local as my personal preferences. Feel free to contact me!!

Best regards,
Alessandro Martins

**Comment by ErichDonGubler** [comment]
Okay, I've taken some time this afternoon to polish up the changes I want from here into separate commits! Thanks for taking the time and getting me to work on this some more -- I'm excited for what you've spurred on,

Bad news first: I've discarded the following:

* Creation of `Contributors.md` -- this isn't something I think is necessary generally. Commit history and the [Contributors tab in Github](https://github.com/ErichDonGubler/vim-sublime-monokai/graphs/contributors) are already fantastic for showing off what contributors have done!
* Additions to the color palette and `Sublime<color>` group. However, this is because of my next point.
* I've also decided not to use your improvements to Java and Python directly -- after playing around with things a bit, I have developed some configuration that I believe to be closer to the goal of being as close to Sublime Text's default highlighting as possible. Python changes are currently in the [`python`](https://github.com/ErichDonGubler/vim-sublime-monokai/tree/python) branch, and I'm checking in changes to Java now.

So, this all said, I have decided to push the following commits to `master`:

* c36aec2 - Improve Java highlighting and officially support mainline `vim` and `vim-java`
* 1735acb - Fix alignment of SublimeBrightWhite in Sublime<color> table
* 5ac4111 - Fix the contrast of TabLineSel colors by making the foreground black
* fe190be - Make MatchParen use underline instead of reversal for, since it's the best solution I've heard so far

These are changes that definitely were prompted by this PR and I'd like to thank you again for the contributions! :) c36aec2 (the first one listed above) specifically has you recorded as the author, since I was able to piggyback your commits into a rebased-then-changed set of changes. I definitely wanted to give you some credit, since you got me started on those improvements in the first place!

I'm closing this PR now, but let me know if you have any other questions or concerns.

**Comment by ErichDonGubler** [comment]
Also, PS: If you want to do a code review on the Java (already in `master`) and Python (in the `python` branch) changes, feel free! I can create a PR for the latter -- I decided to go ahead with the Java changes, since I did a fair amount of reading the syntax files in mainline `vim` and in `rudes/vim-java`.

**Pull request closed without merging**
