### PR TITLE
SpecialKey: Replace SublimeLightBlack2 with SublimePurple

### PR DESCRIPTION
**Pull request by edaplayer**
SpecialKey: It is too dark to see, replace SublimeLightBlack2 with SublimePurple

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
Hey, I'm on mobile right now, otherwise I'd do this myself...could you include a before/after comparison (screenshots), to quickly orient people in this discussion? It took me a few minutes to understand this suggestion since I haven't delved into `SpecialKey` before (this was written before I forked this project), so I had to refer to docs. I think it'd be a great way to bring others up to speed and give input if they have it!

I'll take a look at your solution soon. I agree that the contrast is terrible, and I want to make sure a solution is compatible with this scheme's mission of being as similar to Sublime as possible.

**Comment by edaplayer** [comment]
You can run :map，then see that keymap is too dark，I will upload screenshot when I have time.

**Comment by edaplayer** [comment]
Screenshot with SublimeLightBlack2:
[https://github.com/edaplayer/vim-sublime-monokai/raw/master/screenshots/vimmap_dark.png](url)

**Comment by edaplayer** [comment]
Can you see that screenshot?
https://raw.githubusercontent.com/edaplayer/vim-sublime-monokai/master/screenshots/vimmap_dark.png
[https://raw.githubusercontent.com/edaplayer/vim-sublime-monokai/master/screenshots/vimmap_dark.png](url)

<blockquote></blockquote>

**Comment by ErichDonGubler** [comment]
@edaplayer:I cannot see the second screenshot in your most recent comment -- it appears to be the same link as your second-to-last comment?

**Comment by ErichDonGubler** [comment]
I've changed `SpecialKey` to use a `purple` foreground and `darkblack` background after pushing b59ecf1 to `master`, which I believe fulfills the spirit of this PR. Since I haven't gotten a response from @edaplayer while I've been mostly inactive here, I'm going to take the liberty of going with that approach, considering the original request here fulfilled, and closing this PR.

Other things I noticed with the PR that seem unexpected:

- I think the screenshot I requested was helpful, but ultimately it shouldn't be in the final PR content.
- A commit changing the definition of several Makefile highlight groups also crept in, which seems unrelated to this PR as formulated in the title and OP.

**Pull request closed without merging**
